# Generated by Django 5.2.8 on 2025-11-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_devotee_sabha_type_alter_sabha_sabha_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devotee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='devotee',
            name='age_group',
        ),
        migrations.AddField(
            model_name='devotee',
            name='address_line',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='devotee',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devotee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devotee',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='devotee',
            name='landmark',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='devotee',
            name='zone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='devotee',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Photo URL', max_length=500, null=True),
        ),
    ]
