# Generated by Django 5.2.8 on 2025-11-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_devotee_address_remove_devotee_age_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devotee',
            name='devotee_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='devotee',
            name='devotee_type',
            field=models.CharField(choices=[('haribhakt', 'Haribhakt'), ('gunbhavi', 'Gunbhavi'), ('karyakar', 'Karyakar')], default='haribhakt', max_length=20),
        ),
    ]
